### ISSUE TITLE
Problem with docker-compose and production mode

### ISSUE THREAD

**Issue by fobrice** [afourmy/eNMS#125]
Hi,

When we use the docker-compose in `production` mode we are enable to login.

The `admin` user exists with the `admin` password in the postgres database (in container) and the user is retreived. 

But when after login the app redirect to the page "/dashboard" we get a `403 Access Denied
Full authentication is required to access this resource`.

When we set the line `ENMS_CONFIG_MODE=debug` in the `.env` file the login works.

I don't know if this is linked to the problem but in the scheduler there is a hard link to [sqlite](https://github.com/afourmy/eNMS/blob/25795d8afb008f928e3ff8ab548bc3a29ae953a5/eNMS/main.py#L38) 

regards

**Comment by fobrice** [comment]
Works fine, thank you!

In complement: when in `debug` mode AND `CREATE_EXAMPLES=0`, I get an `internal server error` with a message: 
```
Traceback (most recent call last):                                                                                                                                                                      
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 816, in configure_subclass_mapper                                                                                       
sub_mapper = mapper.polymorphic_map[discriminator]                                                                                                                                                  
KeyError: 'ConfigureBgpService'
[...]
"No such polymorphic_identity %r is defined" % discriminator                                                                                                                                        
AssertionError: No such polymorphic_identity 'ConfigureBgpService' is defined 
```

**Comment by afourmy** [comment]
I guess that's because you first ran eNMS with `CREATE_EXAMPLES=1`, then switched to `CREATE_EXAMPLES=0` (by then, you had a "ConfigureBgpService" in your database, which is why SQL Alchemy complains). Is that what happened ?
If you're using a SQLite database, the fix would be to delete the database (`rm eNMS/database.db`) or drop the ConfigureBgpService table if you have something in the database that you don't want to lose.

The idea is that you're not supposed to change this environment variable after running eNMS, i.e after the database has been created.

**Comment by fobrice** [comment]
Ok, sorry and thank you for you explanation.
