### ISSUE TITLE
multiples commands in a task

### ISSUE THREAD

**Issue by lacheron** [afourmy/eNMS#135]
hi there, awesome tool, maybe this question is a little to simple, but how can i put multiples
commands in a simple task?
\u0007%% Unrecognized command:  \"show config, show log\"
%% Invalid input detected.",

if a run just a show config it works wonderful

Type of servier: NetmikoValidationService

**Comment by afourmy** [comment]
That's not possible because the purpose of this service is to validate the output of a command.
You can either
- create several such services and add them to a workflow
- create a custom service that accepts more than one command

Docs:
https://enms.readthedocs.io/en/latest/services/service_system.html
https://enms.readthedocs.io/en/latest/workflows/workflow_system.html
