### ISSUE TITLE
psycopg2.errors.SyntaxError: type modifier is not allowed for type "text" LINE 4:  device_name TEXT(32768)

### ISSUE THREAD

**Issue by sh1ema** [afourmy/eNMS#156]
Hi, Antoine,
looks like it's the same message with different number. 
I've seen previous message from about 4 mouth ago, but for the life of me I can't find that string anywhere in ./eNMS/.
would you mind to point me where do I find this - Text(DB_STRING_LENGTH)? 
Thank you.

**Comment by afourmy** [comment]
Hi,

There is no such string in the current version.

I'm testing eNMS with SQLite and MySQL, not PostgreSQL and it doesn't work because apparently, you cannot specify a length with the "Text" type, so you migth wanna try to change this line here: https://github.com/afourmy/eNMS/blob/master/eNMS/database/dialect.py#L17

**Comment by sh1ema** [comment]
cool, thanks.

I'll deal with that later, for now I just compiled .sql file and imported it to db.
in case someone need it, 
[eNMS_pgsql_sql.txt](https://github.com/afourmy/eNMS/files/3581079/eNMS_pgsql_sql.txt)
attached.
works great !!, thanks for your great project.
