### ISSUE TITLE
Automatic push to git

### ISSUE THREAD

**Issue by afourmy** [afourmy/eNMS#26]
Let the user configure GIT parameters for automatically pushing to gitlab/github the results of the script.
=> compare scripts results like configs, pings, traceroutes directly on git.

**Comment by ryanmerolle** [comment]
For configs, would you think about automated snapshots pulled from devices and pushed to git based on:
-schedule in calendar
-syslog "configured by user x messages" (after NAPALM logs integration and possibly committed on behalf user in syslog message)
-as a part of automation workflow (committed by user kicking off workflow)

i.e. rancid/oxidized for net box and focused on automation.

Did not want to hit you with a ton of features, just adding to the foundational feature & get your view.

**Comment by ryanmerolle** [comment]
* Having an audit trail would be helpful.  Even adding the userid as a comment for the push would be good enough for version 1 of the feature.
* A handy feature I have seen implemented is setting a timer after logging change made per user in order to group other config changes together in one commit.  In an ideal scenario I have seen: 
  * group all config changes implemented by a user after some timer initiated by first config change
  * prompt user (chatops & web prompt) to extend timer, manually add devices to commit (to address syslog connectivity or log parsing limitations for said device), add a comment, force commit
* I think I was thinking out loud about the workflow.  Creating some function to allow for x automation tool to make a API call to eNMS to pull configs on devices post some push might be nice depending on the tool.  IE it would enhance the automation workflow.

**Comment by afourmy** [comment]
Done: 
Docs:
- https://enms.readthedocs.io/en/latest/services/service_system.html#gitlab-export
- https://enms.readthedocs.io/en/latest/services/default_services.html
