### ISSUE TITLE
custom scripts won't remove from Script Management list

### ISSUE THREAD

**Issue by xplorn** [afourmy/eNMS#81]
using Chrome 67.0.3396.79 on Win10

- modify custom_scripts.py to add another example script:

35,51d34
< ## here's another dumb script
< 
< def job_dumb2(args):
<     task, node, results = args
<     # more dumb stuff 2
<     # results is a dictionnary that contains the logs of the script
<     results[node.name] = {'success': True, 'logs': 'what will be displayed in the logs'}
< 
< 
< dumb2_parameters = {
<     'name': 'Dumb script 2',
<     'description': 'this may be even dumber than the first',
<     'vendor': 'none',
<     'operating_system': 'all',
<     'job_name': 'job_dumb2'
< }
< 
95d77
<         dumb2_parameters,

- restart eNMS, script appears in Script Management

- remove additions to custom_scripts.py

- restart

- newly added script remains in script list

- clearing cookie and browser cache doesn't seem to help, neither does relogging into app.

**Comment by xplorn** [comment]
obvious UI Delete button is obvious..

**Comment by afourmy** [comment]
It is required to restart the app after a custom script is added. In the previous versions, the app was restarting automatically when changing a file because `app.run(use_reloader=True)` was used. Now, the `FLASK_DEBUG` environment variable must be set to 1 to have the same behavior.
I think the problem described here is solved but feel free to reopen the issue if there's anything else.
