### ISSUE TITLE
Using asynchronous library for network configuration

### ISSUE THREAD

**Issue by selfuryon** [afourmy/eNMS#9]
Do you know about the asynchronous library netdev like netmiko for configuring network devices? It can be really fast if there are many devices to configure.

**Comment by afourmy** [comment]
It's a nice project but after consideration, I've decided not to use it because it's only for netmiko, it would be strange to have netmiko tasks asynchronous and not napalm tasks.
With the recent changes that I made, all tasks are executed in parallel on all devices with `multiprocessing` Threadpool.map function (both napalm and netmiko).
It should be fast enough even with > 100 devices.

If you want to have a look at the implementation, it's in _/eNMS/source/scheduling/models.py_
